#!/bin/sh
if [ -z "$CI_METRICS_VERSION" ]; then
	/usr/lib/metrics/.env/bin/pip install --upgrade SDH-CI-Metrics
else
	/usr/lib/metrics/.env/bin/pip install --upgrade SDH-CI-Metrics==$CI_METRICS_VERSION
fi

/usr/lib/metrics/.env/bin/sdh-ci-metrics &
